### ISSUE TITLE
Use FHIR (R4) not QUICK

### ISSUE THREAD

**Issue by psbrandt** [PheMA/cql-on-omop#36]
When using the QUICK data model with the reference implementation, only resources that are explicitly associated with the QUICK profile are retrieved.

I think it would be better to use the base FHIR data model instead, since this would put fewer restrictions on implementations, as they wouldn't be required to associate the QUICK profile with all their FHIR resources.

**Comment by gqjiang** [comment]
Do you know which version of FHIR is currently supported by the CQL API?

**Comment by gqjiang** [comment]
Looks like the latest FHIR version supported is 4.0.1 
https://github.com/cqframework/clinical_quality_language/tree/master/Src/java/cql-to-elm/src/test/resources/org/cqframework/cql/cql2elm/fhir

**Comment by psbrandt** [comment]
CQL itself is data model independent, but it looks like the latest FHIR version supported by the reference implementation is `4.0.1`. It is not an official part of the CQL specification, but the reference implementation use the ModelInfo format (mentioned [here](https://cql.hl7.org/07-physicalrepresentation.html#data-model-references), specified [here](https://cql.hl7.org/elm/schema/modelinfo.xsd)) to represent data models. You can see the ModelInfo files for the various versions [here](https://github.com/cqframework/clinical_quality_language/tree/master/Src/java/quick/src/main/resources/org/hl7/fhir).
