### ISSUE TITLE
Implement FHIR ValueSet Service

### ISSUE THREAD

**Issue by psbrandt** [PheMA/cql-on-omop#43]
We should implement the following interface for resolving value sets from a FHIR server:

https://github.com/PheMA/cql-on-omop/blob/e12d3ba7cc786e5d07895bdb57d0ca1a7ba105a4/src/main/java/edu/phema/elm_to_omop/vocabulary/IValuesetService.java#L8-L12

We will need this in the Workbench API.

**Comment by psbrandt** [comment]
This is probably going to be necessary for the Workbench e2e demo.

**Comment by lrasmus** [comment]
Forgot to tag in PR #52
