### ISSUE TITLE
Execute phenotype Bundles

### ISSUE THREAD

**Issue by lrasmus** [PheMA/cql-on-omop#46]
The system should be able to execute phenotypes that are [represented as a FHIR Bundle](https://github.com/PheMA/phema-workbench-repository/tree/master/bundles)

**Comment by psbrandt** [comment]
Another idea is to accept the URL of a `Composition` resource as input, and then download the full `Composition` document using the `$document` operation. That can be a stretch goal though, and either way, we need to be able to evaluate one of these bundles.

**Comment by lrasmus** [comment]
That's a great idea though - and probably easy to extend to once the core Bundle support exists
